version: "3.8"

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    expose:
      - 8000
    depends_on:
      - database
  
  database:
    container_name: database
    image: postgres:13.0-alpine
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB  
  nginx:
    build: ./nginx
    ports: 
      - 8888:80
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - backend

volumes:
  db_data:
  static_volume:
  media_volume: